### ISSUE TITLE
1.2.2 breaks support for Ember 1.13.x

### ISSUE THREAD

**Issue by kenips** [freshbooks/ember-responsive#47]
Getting `Uncaught TypeError: application.inject is not a function` after upgrading from 1.2.1 to 1.2.2. Looks like removing instance initializer detection kills older Ember support. Perhaps it should be pegged for 1.3.x with clear line drawn for dropping Ember 1.x support?

**Comment by alexBaizeau** [comment]
Ooops, sorry about that, I think that we could follow the advice provided here, to support older version of ember http://emberjs.com/deprecations/v2.x/#toc_initializer-arity

**Comment by alexBaizeau** [comment]
I just published 1.2.3, that should fix it, sorry for the confusion and thanks for reporting the issue!

**Comment by kenips** [comment]
Yep that works. Thank you so much for the speedy fix!
